/* This file was automatically generated by CasADi 3.6.5.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) controller_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};

/* funs:(i0[7],i1[7],i2,i3[7])->(o0[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a7, a8, a9;
  a0=2.0000000000000001e-01;
  a1=2.;
  a2=-5.0000000000000000e-01;
  a3=arg[1]? arg[1][0] : 0;
  a4=casadi_sign(a3);
  a5=1.;
  a4=(a4-a5);
  a4=(a2*a4);
  a6=arg[0]? arg[0][0] : 0;
  a7=-2.8973000000000000e+00;
  a8=(a6-a7);
  a9=casadi_sq(a8);
  a4=(a4/a9);
  a4=(a1*a4);
  a4=(a0+a4);
  a9=(-a3);
  a9=casadi_sign(a9);
  a9=(a9-a5);
  a9=(a2*a9);
  a10=2.8973000000000000e+00;
  a11=(a10-a6);
  a12=casadi_sq(a11);
  a9=(a9/a12);
  a9=(a1*a9);
  a4=(a4+a9);
  a9=1.7000000000000000e+00;
  a12=7.5000000000000000e-01;
  a13=arg[3]? arg[3][0] : 0;
  a6=(a6-a13);
  a13=casadi_sq(a6);
  a14=arg[0]? arg[0][1] : 0;
  a15=arg[3]? arg[3][1] : 0;
  a15=(a14-a15);
  a16=casadi_sq(a15);
  a13=(a13+a16);
  a16=arg[0]? arg[0][2] : 0;
  a17=arg[3]? arg[3][2] : 0;
  a17=(a16-a17);
  a18=casadi_sq(a17);
  a13=(a13+a18);
  a18=arg[0]? arg[0][3] : 0;
  a19=arg[3]? arg[3][3] : 0;
  a19=(a18-a19);
  a20=casadi_sq(a19);
  a13=(a13+a20);
  a20=arg[0]? arg[0][4] : 0;
  a21=arg[3]? arg[3][4] : 0;
  a21=(a20-a21);
  a22=casadi_sq(a21);
  a13=(a13+a22);
  a22=arg[0]? arg[0][5] : 0;
  a23=arg[3]? arg[3][5] : 0;
  a23=(a22-a23);
  a24=casadi_sq(a23);
  a13=(a13+a24);
  a24=arg[0]? arg[0][6] : 0;
  a25=arg[3]? arg[3][6] : 0;
  a25=(a24-a25);
  a26=casadi_sq(a25);
  a13=(a13+a26);
  a13=sqrt(a13);
  a13=(a12*a13);
  a13=casadi_sq(a13);
  a13=(-a13);
  a13=exp(a13);
  a13=(a9*a13);
  a26=2.9999999999999999e-01;
  a13=(a13+a26);
  a27=(a13+a13);
  a27=(a4+a27);
  a28=9.9999999999999995e-07;
  a29=(a27+a28);
  a30=casadi_sq(a29);
  a29=(a29/a30);
  a30=casadi_sign(a3);
  a30=(a30-a5);
  a30=(a2*a30);
  a31=casadi_sq(a8);
  a30=(a30/a31);
  a30=(a1*a30);
  a31=-1.;
  a32=(a31/a8);
  a33=casadi_sq(a3);
  a32=(a32*a33);
  a30=(a30*a32);
  a32=(-a3);
  a32=casadi_sign(a32);
  a32=(a32-a5);
  a32=(a2*a32);
  a33=casadi_sq(a11);
  a32=(a32/a33);
  a32=(a1*a32);
  a33=(a31/a11);
  a34=casadi_sq(a3);
  a33=(a33*a34);
  a32=(a32*a33);
  a30=(a30-a32);
  a32=casadi_sq(a6);
  a33=casadi_sq(a15);
  a32=(a32+a33);
  a33=casadi_sq(a17);
  a32=(a32+a33);
  a33=casadi_sq(a19);
  a32=(a32+a33);
  a33=casadi_sq(a21);
  a32=(a32+a33);
  a33=casadi_sq(a23);
  a32=(a32+a33);
  a33=casadi_sq(a25);
  a32=(a32+a33);
  a32=sqrt(a32);
  a12=(a12*a32);
  a12=casadi_sq(a12);
  a12=(-a12);
  a12=exp(a12);
  a9=(a9*a12);
  a9=(a9+a26);
  a26=(a9+a9);
  a12=(a6+a6);
  a32=-20.;
  a33=casadi_sq(a6);
  a34=casadi_sq(a15);
  a33=(a33+a34);
  a34=casadi_sq(a17);
  a33=(a33+a34);
  a34=casadi_sq(a19);
  a33=(a33+a34);
  a34=casadi_sq(a21);
  a33=(a33+a34);
  a34=casadi_sq(a23);
  a33=(a33+a34);
  a34=casadi_sq(a25);
  a33=(a33+a34);
  a33=sqrt(a33);
  a34=(a32*a33);
  a34=exp(a34);
  a35=1.0000000000000001e-01;
  a36=5.;
  a37=arg[2]? arg[2][0] : 0;
  a36=(a36*a37);
  a35=(a35*a36);
  a37=(a5+a34);
  a35=(a35/a37);
  a34=(a34*a35);
  a32=(a32*a34);
  a33=(a33+a33);
  a32=(a32/a33);
  a12=(a12*a32);
  a33=(a6+a6);
  a34=casadi_sq(a6);
  a35=casadi_sq(a15);
  a34=(a34+a35);
  a35=casadi_sq(a17);
  a34=(a34+a35);
  a35=casadi_sq(a19);
  a34=(a34+a35);
  a35=casadi_sq(a21);
  a34=(a34+a35);
  a35=casadi_sq(a23);
  a34=(a34+a35);
  a35=casadi_sq(a25);
  a34=(a34+a35);
  a34=sqrt(a34);
  a34=(a34+a34);
  a36=(a36/a34);
  a33=(a33*a36);
  a12=(a12+a33);
  a26=(a26*a12);
  a26=(a30+a26);
  a29=(a29*a26);
  a12=6.5000000000000000e+00;
  a33=5.0000000000000000e-01;
  a6=casadi_sq(a6);
  a34=casadi_sq(a15);
  a6=(a6+a34);
  a34=casadi_sq(a17);
  a6=(a6+a34);
  a34=casadi_sq(a19);
  a6=(a6+a34);
  a34=casadi_sq(a21);
  a6=(a6+a34);
  a34=casadi_sq(a23);
  a6=(a6+a34);
  a34=casadi_sq(a25);
  a6=(a6+a34);
  a6=sqrt(a6);
  a34=2.0000000000000000e-02;
  a6=(a6-a34);
  a6=(a2*a6);
  a6=tanh(a6);
  a6=(a6+a5);
  a6=(a33*a6);
  a12=(a12*a6);
  a6=1.0000000000000000e-02;
  a12=(a12+a6);
  a6=0.;
  a34=-4.5000000000000001e-01;
  a35=casadi_sq(a3);
  a37=arg[1]? arg[1][1] : 0;
  a38=casadi_sq(a37);
  a35=(a35+a38);
  a38=arg[1]? arg[1][2] : 0;
  a39=casadi_sq(a38);
  a35=(a35+a39);
  a39=arg[1]? arg[1][3] : 0;
  a40=casadi_sq(a39);
  a35=(a35+a40);
  a40=arg[1]? arg[1][4] : 0;
  a41=casadi_sq(a40);
  a35=(a35+a41);
  a41=arg[1]? arg[1][5] : 0;
  a42=casadi_sq(a41);
  a35=(a35+a42);
  a42=arg[1]? arg[1][6] : 0;
  a43=casadi_sq(a42);
  a35=(a35+a43);
  a34=(a34*a35);
  a34=(a34-a33);
  a34=tanh(a34);
  a34=(a34+a5);
  a33=(a33*a34);
  a4=(a4+a28);
  a34=casadi_sq(a4);
  a4=(a4/a34);
  a4=(a4*a30);
  a4=(a1*a4);
  a4=(a3*a4);
  a34=casadi_sign(a37);
  a34=(a34-a5);
  a34=(a2*a34);
  a35=-1.7627999999999999e+00;
  a35=(a14-a35);
  a43=casadi_sq(a35);
  a34=(a34/a43);
  a34=(a1*a34);
  a34=(a0+a34);
  a43=(-a37);
  a43=casadi_sign(a43);
  a43=(a43-a5);
  a43=(a2*a43);
  a44=1.7627999999999999e+00;
  a44=(a44-a14);
  a14=casadi_sq(a44);
  a43=(a43/a14);
  a43=(a1*a43);
  a34=(a34+a43);
  a43=(a34+a28);
  a14=casadi_sq(a43);
  a43=(a43/a14);
  a14=casadi_sign(a37);
  a14=(a14-a5);
  a14=(a2*a14);
  a45=casadi_sq(a35);
  a14=(a14/a45);
  a14=(a1*a14);
  a45=(a31/a35);
  a46=casadi_sq(a37);
  a45=(a45*a46);
  a14=(a14*a45);
  a45=(-a37);
  a45=casadi_sign(a45);
  a45=(a45-a5);
  a45=(a2*a45);
  a46=casadi_sq(a44);
  a45=(a45/a46);
  a45=(a1*a45);
  a46=(a31/a44);
  a47=casadi_sq(a37);
  a46=(a46*a47);
  a45=(a45*a46);
  a14=(a14-a45);
  a43=(a43*a14);
  a43=(a1*a43);
  a43=(a37*a43);
  a4=(a4+a43);
  a43=casadi_sign(a38);
  a43=(a43-a5);
  a43=(a2*a43);
  a45=(a16-a7);
  a46=casadi_sq(a45);
  a43=(a43/a46);
  a43=(a1*a43);
  a43=(a0+a43);
  a46=(-a38);
  a46=casadi_sign(a46);
  a46=(a46-a5);
  a46=(a2*a46);
  a16=(a10-a16);
  a47=casadi_sq(a16);
  a46=(a46/a47);
  a46=(a1*a46);
  a43=(a43+a46);
  a46=(a43+a28);
  a47=casadi_sq(a46);
  a46=(a46/a47);
  a47=casadi_sign(a38);
  a47=(a47-a5);
  a47=(a2*a47);
  a48=casadi_sq(a45);
  a47=(a47/a48);
  a47=(a1*a47);
  a48=(a31/a45);
  a49=casadi_sq(a38);
  a48=(a48*a49);
  a47=(a47*a48);
  a48=(-a38);
  a48=casadi_sign(a48);
  a48=(a48-a5);
  a48=(a2*a48);
  a49=casadi_sq(a16);
  a48=(a48/a49);
  a48=(a1*a48);
  a49=(a31/a16);
  a50=casadi_sq(a38);
  a49=(a49*a50);
  a48=(a48*a49);
  a47=(a47-a48);
  a46=(a46*a47);
  a46=(a1*a46);
  a46=(a38*a46);
  a4=(a4+a46);
  a46=casadi_sign(a39);
  a46=(a46-a5);
  a46=(a2*a46);
  a48=-3.0718000000000001e+00;
  a48=(a18-a48);
  a49=casadi_sq(a48);
  a46=(a46/a49);
  a46=(a1*a46);
  a46=(a0+a46);
  a49=(-a39);
  a49=casadi_sign(a49);
  a49=(a49-a5);
  a49=(a2*a49);
  a50=-6.9800000000000001e-02;
  a50=(a50-a18);
  a18=casadi_sq(a50);
  a49=(a49/a18);
  a49=(a1*a49);
  a46=(a46+a49);
  a49=(a46+a28);
  a18=casadi_sq(a49);
  a49=(a49/a18);
  a18=casadi_sign(a39);
  a18=(a18-a5);
  a18=(a2*a18);
  a51=casadi_sq(a48);
  a18=(a18/a51);
  a18=(a1*a18);
  a51=(a31/a48);
  a52=casadi_sq(a39);
  a51=(a51*a52);
  a18=(a18*a51);
  a51=(-a39);
  a51=casadi_sign(a51);
  a51=(a51-a5);
  a51=(a2*a51);
  a52=casadi_sq(a50);
  a51=(a51/a52);
  a51=(a1*a51);
  a52=(a31/a50);
  a53=casadi_sq(a39);
  a52=(a52*a53);
  a51=(a51*a52);
  a18=(a18-a51);
  a49=(a49*a18);
  a49=(a1*a49);
  a49=(a39*a49);
  a4=(a4+a49);
  a49=casadi_sign(a40);
  a49=(a49-a5);
  a49=(a2*a49);
  a51=(a20-a7);
  a52=casadi_sq(a51);
  a49=(a49/a52);
  a49=(a1*a49);
  a49=(a0+a49);
  a52=(-a40);
  a52=casadi_sign(a52);
  a52=(a52-a5);
  a52=(a2*a52);
  a20=(a10-a20);
  a53=casadi_sq(a20);
  a52=(a52/a53);
  a52=(a1*a52);
  a49=(a49+a52);
  a52=(a49+a28);
  a53=casadi_sq(a52);
  a52=(a52/a53);
  a53=casadi_sign(a40);
  a53=(a53-a5);
  a53=(a2*a53);
  a54=casadi_sq(a51);
  a53=(a53/a54);
  a53=(a1*a53);
  a54=(a31/a51);
  a55=casadi_sq(a40);
  a54=(a54*a55);
  a53=(a53*a54);
  a54=(-a40);
  a54=casadi_sign(a54);
  a54=(a54-a5);
  a54=(a2*a54);
  a55=casadi_sq(a20);
  a54=(a54/a55);
  a54=(a1*a54);
  a55=(a31/a20);
  a56=casadi_sq(a40);
  a55=(a55*a56);
  a54=(a54*a55);
  a53=(a53-a54);
  a52=(a52*a53);
  a52=(a1*a52);
  a52=(a40*a52);
  a4=(a4+a52);
  a52=casadi_sign(a41);
  a52=(a52-a5);
  a52=(a2*a52);
  a54=-1.7500000000000002e-02;
  a54=(a22-a54);
  a55=casadi_sq(a54);
  a52=(a52/a55);
  a52=(a1*a52);
  a52=(a0+a52);
  a55=(-a41);
  a55=casadi_sign(a55);
  a55=(a55-a5);
  a55=(a2*a55);
  a56=3.7524999999999999e+00;
  a56=(a56-a22);
  a22=casadi_sq(a56);
  a55=(a55/a22);
  a55=(a1*a55);
  a52=(a52+a55);
  a55=(a52+a28);
  a22=casadi_sq(a55);
  a55=(a55/a22);
  a22=casadi_sign(a41);
  a22=(a22-a5);
  a22=(a2*a22);
  a57=casadi_sq(a54);
  a22=(a22/a57);
  a22=(a1*a22);
  a57=(a31/a54);
  a58=casadi_sq(a41);
  a57=(a57*a58);
  a22=(a22*a57);
  a57=(-a41);
  a57=casadi_sign(a57);
  a57=(a57-a5);
  a57=(a2*a57);
  a58=casadi_sq(a56);
  a57=(a57/a58);
  a57=(a1*a57);
  a58=(a31/a56);
  a59=casadi_sq(a41);
  a58=(a58*a59);
  a57=(a57*a58);
  a22=(a22-a57);
  a55=(a55*a22);
  a55=(a1*a55);
  a55=(a41*a55);
  a4=(a4+a55);
  a55=casadi_sign(a42);
  a55=(a55-a5);
  a55=(a2*a55);
  a7=(a24-a7);
  a57=casadi_sq(a7);
  a55=(a55/a57);
  a55=(a1*a55);
  a55=(a0+a55);
  a57=(-a42);
  a57=casadi_sign(a57);
  a57=(a57-a5);
  a57=(a2*a57);
  a10=(a10-a24);
  a24=casadi_sq(a10);
  a57=(a57/a24);
  a57=(a1*a57);
  a55=(a55+a57);
  a57=(a55+a28);
  a24=casadi_sq(a57);
  a57=(a57/a24);
  a24=casadi_sign(a42);
  a24=(a24-a5);
  a24=(a2*a24);
  a58=casadi_sq(a7);
  a24=(a24/a58);
  a24=(a1*a24);
  a58=(a31/a7);
  a59=casadi_sq(a42);
  a58=(a58*a59);
  a24=(a24*a58);
  a58=(-a42);
  a58=casadi_sign(a58);
  a58=(a58-a5);
  a58=(a2*a58);
  a59=casadi_sq(a10);
  a58=(a58/a59);
  a58=(a1*a58);
  a31=(a31/a10);
  a59=casadi_sq(a42);
  a31=(a31*a59);
  a58=(a58*a31);
  a24=(a24-a58);
  a57=(a57*a24);
  a57=(a1*a57);
  a57=(a42*a57);
  a4=(a4+a57);
  a57=(a1*a3);
  a57=(a3*a57);
  a58=(a1*a37);
  a58=(a37*a58);
  a57=(a57+a58);
  a58=(a1*a38);
  a58=(a38*a58);
  a57=(a57+a58);
  a58=(a1*a39);
  a58=(a39*a58);
  a57=(a57+a58);
  a58=(a1*a40);
  a58=(a40*a58);
  a57=(a57+a58);
  a58=(a1*a41);
  a58=(a41*a58);
  a57=(a57+a58);
  a58=(a1*a42);
  a58=(a42*a58);
  a57=(a57+a58);
  a57=(a28+a57);
  a4=(a4/a57);
  a4=(a33*a4);
  a33=(a5-a33);
  a27=(a27+a28);
  a57=casadi_sq(a27);
  a27=(a27/a57);
  a27=(a27*a26);
  a27=(a1*a27);
  a27=(a3*a27);
  a26=(a13+a13);
  a34=(a34+a26);
  a26=(a34+a28);
  a57=casadi_sq(a26);
  a26=(a26/a57);
  a57=(a9+a9);
  a58=(a15+a15);
  a58=(a58*a32);
  a15=(a15+a15);
  a15=(a15*a36);
  a58=(a58+a15);
  a57=(a57*a58);
  a57=(a14+a57);
  a26=(a26*a57);
  a26=(a1*a26);
  a26=(a37*a26);
  a27=(a27+a26);
  a26=(a13+a13);
  a43=(a43+a26);
  a26=(a43+a28);
  a58=casadi_sq(a26);
  a26=(a26/a58);
  a58=(a9+a9);
  a15=(a17+a17);
  a15=(a15*a32);
  a17=(a17+a17);
  a17=(a17*a36);
  a15=(a15+a17);
  a58=(a58*a15);
  a58=(a47+a58);
  a26=(a26*a58);
  a26=(a1*a26);
  a26=(a38*a26);
  a27=(a27+a26);
  a26=(a13+a13);
  a46=(a46+a26);
  a26=(a46+a28);
  a15=casadi_sq(a26);
  a26=(a26/a15);
  a15=(a9+a9);
  a17=(a19+a19);
  a17=(a17*a32);
  a19=(a19+a19);
  a19=(a19*a36);
  a17=(a17+a19);
  a15=(a15*a17);
  a15=(a18+a15);
  a26=(a26*a15);
  a26=(a1*a26);
  a26=(a39*a26);
  a27=(a27+a26);
  a26=(a13+a13);
  a49=(a49+a26);
  a26=(a49+a28);
  a17=casadi_sq(a26);
  a26=(a26/a17);
  a17=(a9+a9);
  a19=(a21+a21);
  a19=(a19*a32);
  a21=(a21+a21);
  a21=(a21*a36);
  a19=(a19+a21);
  a17=(a17*a19);
  a17=(a53+a17);
  a26=(a26*a17);
  a26=(a1*a26);
  a26=(a40*a26);
  a27=(a27+a26);
  a26=(a13+a13);
  a52=(a52+a26);
  a26=(a52+a28);
  a19=casadi_sq(a26);
  a26=(a26/a19);
  a19=(a9+a9);
  a21=(a23+a23);
  a21=(a21*a32);
  a23=(a23+a23);
  a23=(a23*a36);
  a21=(a21+a23);
  a19=(a19*a21);
  a19=(a22+a19);
  a26=(a26*a19);
  a26=(a1*a26);
  a26=(a41*a26);
  a27=(a27+a26);
  a13=(a13+a13);
  a55=(a55+a13);
  a13=(a55+a28);
  a26=casadi_sq(a13);
  a13=(a13/a26);
  a9=(a9+a9);
  a26=(a25+a25);
  a26=(a26*a32);
  a25=(a25+a25);
  a25=(a25*a36);
  a26=(a26+a25);
  a9=(a9*a26);
  a9=(a24+a9);
  a13=(a13*a9);
  a13=(a1*a13);
  a13=(a42*a13);
  a27=(a27+a13);
  a13=(a1*a3);
  a13=(a3*a13);
  a26=(a1*a37);
  a26=(a37*a26);
  a13=(a13+a26);
  a26=(a1*a38);
  a26=(a38*a26);
  a13=(a13+a26);
  a26=(a1*a39);
  a26=(a39*a26);
  a13=(a13+a26);
  a26=(a1*a40);
  a26=(a40*a26);
  a13=(a13+a26);
  a26=(a1*a41);
  a26=(a41*a26);
  a13=(a13+a26);
  a26=(a1*a42);
  a26=(a42*a26);
  a13=(a13+a26);
  a13=(a28+a13);
  a27=(a27/a13);
  a33=(a33*a27);
  a4=(a4+a33);
  a33=(a8+a8);
  a27=casadi_sign(a3);
  a27=(a27-a5);
  a27=(a2*a27);
  a8=casadi_sq(a8);
  a27=(a27/a8);
  a8=(a27/a8);
  a13=casadi_sq(a3);
  a13=(a8*a13);
  a13=(a33*a13);
  a26=(a3+a3);
  a8=(a8*a26);
  a33=(a33*a8);
  a33=(a33*a3);
  a13=(a13-a33);
  a33=(a11+a11);
  a8=(-a3);
  a8=casadi_sign(a8);
  a8=(a8-a5);
  a8=(a2*a8);
  a11=casadi_sq(a11);
  a8=(a8/a11);
  a11=(a8/a11);
  a26=(a3+a3);
  a26=(a11*a26);
  a26=(a33*a26);
  a26=(a26*a3);
  a25=casadi_sq(a3);
  a11=(a11*a25);
  a33=(a33*a11);
  a26=(a26-a33);
  a13=(a13+a26);
  a30=(a30-a13);
  a30=(a3*a30);
  a13=(a35+a35);
  a26=casadi_sign(a37);
  a26=(a26-a5);
  a26=(a2*a26);
  a35=casadi_sq(a35);
  a26=(a26/a35);
  a35=(a26/a35);
  a33=casadi_sq(a37);
  a33=(a35*a33);
  a33=(a13*a33);
  a11=(a37+a37);
  a35=(a35*a11);
  a13=(a13*a35);
  a13=(a13*a37);
  a33=(a33-a13);
  a13=(a44+a44);
  a35=(-a37);
  a35=casadi_sign(a35);
  a35=(a35-a5);
  a35=(a2*a35);
  a44=casadi_sq(a44);
  a35=(a35/a44);
  a44=(a35/a44);
  a11=(a37+a37);
  a11=(a44*a11);
  a11=(a13*a11);
  a11=(a11*a37);
  a25=casadi_sq(a37);
  a44=(a44*a25);
  a13=(a13*a44);
  a11=(a11-a13);
  a33=(a33+a11);
  a14=(a14-a33);
  a14=(a37*a14);
  a30=(a30+a14);
  a14=(a45+a45);
  a33=casadi_sign(a38);
  a33=(a33-a5);
  a33=(a2*a33);
  a45=casadi_sq(a45);
  a33=(a33/a45);
  a45=(a33/a45);
  a11=casadi_sq(a38);
  a11=(a45*a11);
  a11=(a14*a11);
  a13=(a38+a38);
  a45=(a45*a13);
  a14=(a14*a45);
  a14=(a14*a38);
  a11=(a11-a14);
  a14=(a16+a16);
  a45=(-a38);
  a45=casadi_sign(a45);
  a45=(a45-a5);
  a45=(a2*a45);
  a16=casadi_sq(a16);
  a45=(a45/a16);
  a16=(a45/a16);
  a13=(a38+a38);
  a13=(a16*a13);
  a13=(a14*a13);
  a13=(a13*a38);
  a44=casadi_sq(a38);
  a16=(a16*a44);
  a14=(a14*a16);
  a13=(a13-a14);
  a11=(a11+a13);
  a47=(a47-a11);
  a47=(a38*a47);
  a30=(a30+a47);
  a47=(a48+a48);
  a11=casadi_sign(a39);
  a11=(a11-a5);
  a11=(a2*a11);
  a48=casadi_sq(a48);
  a11=(a11/a48);
  a48=(a11/a48);
  a13=casadi_sq(a39);
  a13=(a48*a13);
  a13=(a47*a13);
  a14=(a39+a39);
  a48=(a48*a14);
  a47=(a47*a48);
  a47=(a47*a39);
  a13=(a13-a47);
  a47=(a50+a50);
  a48=(-a39);
  a48=casadi_sign(a48);
  a48=(a48-a5);
  a48=(a2*a48);
  a50=casadi_sq(a50);
  a48=(a48/a50);
  a50=(a48/a50);
  a14=(a39+a39);
  a14=(a50*a14);
  a14=(a47*a14);
  a14=(a14*a39);
  a16=casadi_sq(a39);
  a50=(a50*a16);
  a47=(a47*a50);
  a14=(a14-a47);
  a13=(a13+a14);
  a18=(a18-a13);
  a18=(a39*a18);
  a30=(a30+a18);
  a18=(a51+a51);
  a13=casadi_sign(a40);
  a13=(a13-a5);
  a13=(a2*a13);
  a51=casadi_sq(a51);
  a13=(a13/a51);
  a51=(a13/a51);
  a14=casadi_sq(a40);
  a14=(a51*a14);
  a14=(a18*a14);
  a47=(a40+a40);
  a51=(a51*a47);
  a18=(a18*a51);
  a18=(a18*a40);
  a14=(a14-a18);
  a18=(a20+a20);
  a51=(-a40);
  a51=casadi_sign(a51);
  a51=(a51-a5);
  a51=(a2*a51);
  a20=casadi_sq(a20);
  a51=(a51/a20);
  a20=(a51/a20);
  a47=(a40+a40);
  a47=(a20*a47);
  a47=(a18*a47);
  a47=(a47*a40);
  a50=casadi_sq(a40);
  a20=(a20*a50);
  a18=(a18*a20);
  a47=(a47-a18);
  a14=(a14+a47);
  a53=(a53-a14);
  a53=(a40*a53);
  a30=(a30+a53);
  a53=(a54+a54);
  a14=casadi_sign(a41);
  a14=(a14-a5);
  a14=(a2*a14);
  a54=casadi_sq(a54);
  a14=(a14/a54);
  a54=(a14/a54);
  a47=casadi_sq(a41);
  a47=(a54*a47);
  a47=(a53*a47);
  a18=(a41+a41);
  a54=(a54*a18);
  a53=(a53*a54);
  a53=(a53*a41);
  a47=(a47-a53);
  a53=(a56+a56);
  a54=(-a41);
  a54=casadi_sign(a54);
  a54=(a54-a5);
  a54=(a2*a54);
  a56=casadi_sq(a56);
  a54=(a54/a56);
  a56=(a54/a56);
  a18=(a41+a41);
  a18=(a56*a18);
  a18=(a53*a18);
  a18=(a18*a41);
  a20=casadi_sq(a41);
  a56=(a56*a20);
  a53=(a53*a56);
  a18=(a18-a53);
  a47=(a47+a18);
  a22=(a22-a47);
  a22=(a41*a22);
  a30=(a30+a22);
  a22=(a7+a7);
  a47=casadi_sign(a42);
  a47=(a47-a5);
  a47=(a2*a47);
  a7=casadi_sq(a7);
  a47=(a47/a7);
  a7=(a47/a7);
  a18=casadi_sq(a42);
  a18=(a7*a18);
  a18=(a22*a18);
  a53=(a42+a42);
  a7=(a7*a53);
  a22=(a22*a7);
  a22=(a22*a42);
  a18=(a18-a22);
  a22=(a10+a10);
  a7=(-a42);
  a7=casadi_sign(a7);
  a7=(a7-a5);
  a2=(a2*a7);
  a10=casadi_sq(a10);
  a2=(a2/a10);
  a10=(a2/a10);
  a7=(a42+a42);
  a7=(a10*a7);
  a7=(a22*a7);
  a7=(a7*a42);
  a5=casadi_sq(a42);
  a10=(a10*a5);
  a22=(a22*a10);
  a7=(a7-a22);
  a18=(a18+a7);
  a24=(a24-a18);
  a24=(a42*a24);
  a30=(a30+a24);
  a27=(a1*a27);
  a27=(a0+a27);
  a8=(a1*a8);
  a27=(a27+a8);
  a27=(a27*a3);
  a27=(a3*a27);
  a26=(a1*a26);
  a26=(a0+a26);
  a35=(a1*a35);
  a26=(a26+a35);
  a26=(a26*a37);
  a26=(a37*a26);
  a27=(a27+a26);
  a33=(a1*a33);
  a33=(a0+a33);
  a45=(a1*a45);
  a33=(a33+a45);
  a33=(a33*a38);
  a33=(a38*a33);
  a27=(a27+a33);
  a11=(a1*a11);
  a11=(a0+a11);
  a48=(a1*a48);
  a11=(a11+a48);
  a11=(a11*a39);
  a11=(a39*a11);
  a27=(a27+a11);
  a13=(a1*a13);
  a13=(a0+a13);
  a51=(a1*a51);
  a13=(a13+a51);
  a13=(a13*a40);
  a13=(a40*a13);
  a27=(a27+a13);
  a14=(a1*a14);
  a14=(a0+a14);
  a54=(a1*a54);
  a14=(a14+a54);
  a14=(a14*a41);
  a14=(a41*a14);
  a27=(a27+a14);
  a47=(a1*a47);
  a0=(a0+a47);
  a1=(a1*a2);
  a0=(a0+a1);
  a0=(a0*a42);
  a0=(a42*a0);
  a27=(a27+a0);
  a27=(a28+a27);
  a30=(a30/a27);
  a30=(a4-a30);
  a6=casadi_fmax(a6,a30);
  a12=(a12+a6);
  a12=(a12-a4);
  a3=(a12*a3);
  a29=(a29+a3);
  a29=(-a29);
  if (res[0]!=0) res[0][0]=a29;
  a34=(a34+a28);
  a29=casadi_sq(a34);
  a34=(a34/a29);
  a34=(a34*a57);
  a37=(a12*a37);
  a34=(a34+a37);
  a34=(-a34);
  if (res[0]!=0) res[0][1]=a34;
  a43=(a43+a28);
  a34=casadi_sq(a43);
  a43=(a43/a34);
  a43=(a43*a58);
  a38=(a12*a38);
  a43=(a43+a38);
  a43=(-a43);
  if (res[0]!=0) res[0][2]=a43;
  a46=(a46+a28);
  a43=casadi_sq(a46);
  a46=(a46/a43);
  a46=(a46*a15);
  a39=(a12*a39);
  a46=(a46+a39);
  a46=(-a46);
  if (res[0]!=0) res[0][3]=a46;
  a49=(a49+a28);
  a46=casadi_sq(a49);
  a49=(a49/a46);
  a49=(a49*a17);
  a40=(a12*a40);
  a49=(a49+a40);
  a49=(-a49);
  if (res[0]!=0) res[0][4]=a49;
  a52=(a52+a28);
  a49=casadi_sq(a52);
  a52=(a52/a49);
  a52=(a52*a19);
  a41=(a12*a41);
  a52=(a52+a41);
  a52=(-a52);
  if (res[0]!=0) res[0][5]=a52;
  a55=(a55+a28);
  a28=casadi_sq(a55);
  a55=(a55/a28);
  a55=(a55*a9);
  a12=(a12*a42);
  a55=(a55+a12);
  a55=(-a55);
  if (res[0]!=0) res[0][6]=a55;
  return 0;
}

CASADI_SYMBOL_EXPORT int funs(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int funs_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int funs_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void funs_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int funs_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void funs_release(int mem) {
}

CASADI_SYMBOL_EXPORT void funs_incref(void) {
}

CASADI_SYMBOL_EXPORT void funs_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int funs_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int funs_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real funs_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* funs_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* funs_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* funs_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* funs_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int funs_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int funs_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
