problem:
  environment:
    number_cuboids:
      dynamic: 0
      static: 0
    number_planes: 0
    number_spheres:
      dynamic: 0
      static: 0
  goal:
    goal_definition:
      subgoal0:
        weight: 0.5
        is_primary_goal: True
        indices: [0, 1, 2, 3, 4, 5, 6]
        desired_position: [-1.0, 0.7, 0.5, -1.501, 0.0, 1.8675, 0.0]
        epsilon: 0.05
        type: staticJointSpaceSubGoal
  joint_limits:
    lower_limits:
    - -2.8973
    - -1.7628
    - -2.8973
    - -3.0718
    - -2.8973
    - -0.0175
    - -2.8973
    upper_limits:
    - 2.8973
    - 1.7628
    - 2.8973
    - -0.0698
    - 2.8973
    - 3.7525
    - 2.8973
  robot_representation:
    collision_links: {}
    self_collision_pairs: {}
fabrics:
  limit_geometry: -1.0 / (x ** 1) * xdot ** 2
  limit_finsler: 1.0/(x**2) * (-0.5 * (ca.sign(xdot) - 1)) * xdot**2
  collision_geometry: -0.2 / (x ** 1) * xdot ** 2
  collision_finsler:  0.2/(x**2) * (-0.5 * (ca.sign(xdot) - 1)) * xdot ** 2

